package com.demo.entities;
// Generated Nov 21, 2023, 12:19:37 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name = "post")
public class Post implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String subject;
	private Date postdate;
	private int bedroom;
	private int bathroom;
	private double price;
	private double deposit;
	private String area;
	private String description;
	private String address;
	private boolean status;
	private Set<Image> images = new HashSet<Image>(0);

	public Post() {
	}

	public Post(Account account, String subject, Date postdate, int bedroom, int bathroom, double price, double deposit,
			String area, String description, String address, boolean status) {
		this.account = account;
		this.subject = subject;
		this.postdate = postdate;
		this.bedroom = bedroom;
		this.bathroom = bathroom;
		this.price = price;
		this.deposit = deposit;
		this.area = area;
		this.description = description;
		this.address = address;
		this.status = status;
	}

	public Post(Account account, String subject, Date postdate, int bedroom, int bathroom, double price, double deposit,
			String area, String description, String address, boolean status, Set<Image> images) {
		this.account = account;
		this.subject = subject;
		this.postdate = postdate;
		this.bedroom = bedroom;
		this.bathroom = bathroom;
		this.price = price;
		this.deposit = deposit;
		this.area = area;
		this.description = description;
		this.address = address;
		this.status = status;
		this.images = images;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountid", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "subject", nullable = false, length = 250)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "postdate", nullable = false, length = 10)
	public Date getPostdate() {
		return this.postdate;
	}

	public void setPostdate(Date postdate) {
		this.postdate = postdate;
	}

	@Column(name = "bedroom", nullable = false)
	public int getBedroom() {
		return this.bedroom;
	}

	public void setBedroom(int bedroom) {
		this.bedroom = bedroom;
	}

	@Column(name = "bathroom", nullable = false)
	public int getBathroom() {
		return this.bathroom;
	}

	public void setBathroom(int bathroom) {
		this.bathroom = bathroom;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "deposit", nullable = false, precision = 22, scale = 0)
	public double getDeposit() {
		return this.deposit;
	}

	public void setDeposit(double deposit) {
		this.deposit = deposit;
	}

	@Column(name = "area", nullable = false, length = 250)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "description", nullable = false, length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "address", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "post")
	public Set<Image> getImages() {
		return this.images;
	}

	public void setImages(Set<Image> images) {
		this.images = images;
	}

}
