package com.demo.entities;
// Generated Nov 21, 2023, 12:19:37 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Systemapartment generated by hbm2java
 */
@Entity
@Table(name = "systemapartment")
public class Systemapartment implements java.io.Serializable {

	private Integer id;
	private Branch branch;
	private String subject;
	private int bedroom;
	private int bathroom;
	private double price;
	private double deposit;
	private String area;
	private String description;
	private boolean status;
	private Set<Contract> contracts = new HashSet<Contract>(0);

	public Systemapartment() {
	}

	public Systemapartment(Branch branch, String subject, int bedroom, int bathroom, double price, double deposit,
			String area, String description, boolean status) {
		this.branch = branch;
		this.subject = subject;
		this.bedroom = bedroom;
		this.bathroom = bathroom;
		this.price = price;
		this.deposit = deposit;
		this.area = area;
		this.description = description;
		this.status = status;
	}

	public Systemapartment(Branch branch, String subject, int bedroom, int bathroom, double price, double deposit,
			String area, String description, boolean status, Set<Contract> contracts) {
		this.branch = branch;
		this.subject = subject;
		this.bedroom = bedroom;
		this.bathroom = bathroom;
		this.price = price;
		this.deposit = deposit;
		this.area = area;
		this.description = description;
		this.status = status;
		this.contracts = contracts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branchid", nullable = false)
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@Column(name = "subject", nullable = false, length = 250)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "bedroom", nullable = false)
	public int getBedroom() {
		return this.bedroom;
	}

	public void setBedroom(int bedroom) {
		this.bedroom = bedroom;
	}

	@Column(name = "bathroom", nullable = false)
	public int getBathroom() {
		return this.bathroom;
	}

	public void setBathroom(int bathroom) {
		this.bathroom = bathroom;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "deposit", nullable = false, precision = 22, scale = 0)
	public double getDeposit() {
		return this.deposit;
	}

	public void setDeposit(double deposit) {
		this.deposit = deposit;
	}

	@Column(name = "area", nullable = false, length = 250)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "systemapartment")
	public Set<Contract> getContracts() {
		return this.contracts;
	}

	public void setContracts(Set<Contract> contracts) {
		this.contracts = contracts;
	}

}
